### ISSUE TITLE
Server Error | TingoDB: ACTIVE_COLLECTIONS.include is not a function

### ISSUE THREAD

**Issue by TheCodeCrafter** [RainingChain/rainingchain#11]
Error Level 1:                                                                                                                                             
TypeError: ACTIVE_COLLECTIONS.includes is not a function                                                                                                   
    at /home/cabox/workspace/server/private/Db_tingodb.js:54:70                                                                                            
    at Array.forEach (native)                                                                                                                              
    at Object.DbObj_one2.require (/home/cabox/workspace/server/private/Db_tingodb.js:51:19)                                                                
    at Object.exports.init_app (/home/cabox/workspace/server/private/App_private.js:136:15)                                                                
    at Object.<anonymous> (/home/cabox/workspace/app.js:86:45)                                                                                             
    at Module._compile (module.js:399:26)                                                                                                                  
    at Object.Module._extensions..js (module.js:406:10)                                                                                                    
    at Module.load (module.js:345:32)                                                                                                                      
    at Function.Module._load (module.js:302:12)                                                                                                            
    at Function.Module.runMain (module.js:431:10)   

Can anyone help me out here? Trying to learn to make a multiplayer game using RainingChain's awesome tips, but I first wish to examine his full game ;)

Thanks,
TheCodeCrafter

**Comment by RainingChain** [comment]
You are using a old Nodejs version that doesn't support ES6. Upgrade your Nodejs version.
